### ISSUE TITLE
Adding "limit" argument

### ISSUE THREAD

**Issue by mohadelrezk** [OpenGovIntelligence/json-qb-api-implementation#5]
_From @mohadelrezk on December 2, 2016 11:7_

In most of queries a LIMIT argument will help to handle bigger data sets.
Specially for (values) queries. 

_Copied from original issue: zeginis/JSON-QB-REST-API#6_

**Comment by mohadelrezk** [comment]
_From @zeginis on December 2, 2016 11:22_

Yes indeed this is needed! We need to adopt a LIMIT strategy for all the queries

**Comment by zeginis** [comment]
Waiting for the API specification for details how to implement pagination

**Comment by mohadelrezk** [comment]
In README file **limit** is taged as optional for **slice?** query, but if not provided you get a null pointer exception error as follows:

> HTTP ERROR 500
> Problem accessing /slice. Reason:

    Server Error
> Caused by:
    
java.lang.NullPointerException
	at org.certh.jsonqb.core.SPARQLresultTransformer.toObservationList(SPARQLresultTransformer.java:316)
	at org.certh.jsonqb.core.CubeSPARQL.getSlice(CubeSPARQL.java:284)
	at org.certh.jsonqb.api.impl.ImplRESTapi.getSlice(ImplRESTapi.java:374)
